version: "3.8"

services:
  redis:
    image: redis
    restart: unless-stopped
  hello-backend:
    build: ./backend
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - 8080:8080
  hello-frontend:
    build: ./frontend
    ports:
      - 5000:5000
